const mongoose = require("mongoose");
const favourite = require("./favourite");

// Id's will be generated by mongoose itself
const homeSchema = new mongoose.Schema({
    houseName: { type: String, required: true },
    price: { type: Number, required: true },
    date: { type: Date, required: true },
    location: { type: String, required: true },
    image: { type: String, required: true },
    description: String,
});

homeSchema.pre("findOneAndDelete", async function () {
    const homeId = this.getFilter()?._id;

    if (homeId) {
        await favourite.deleteMany({ houseId: homeId });
    }
});

module.exports = mongoose.model("Home", homeSchema);
