const mongoose = require("mongoose");

// Id's will be generated by mongoose itself
const homeSchema = mongoose.connect({
    houseName: { type: String, required: True },
    price: { type: Number, required: True },
    date: { type: Date, required: True },
    location: { type: String, required: True },
    image: { type: String, required: True },
    description: String,
});

module.exports = mongoose.model('Home', homeSchema)