const mongoose = require("mongoose");

// Id's will be generated by mongoose itself
const homeSchema = mongoose.Schema({
    houseName: { type: String, required: true },
    price: { type: Number, required: true },
    date: { type: Date, required: true },
    location: { type: String, required: true },
    image: { type: String, required: true },
    description: String,
});

module.exports = mongoose.model("Home", homeSchema)